function [ potential ] = getHuber(image,delta)
% 获取图像的huber势函数的表达式，用于osl_em重建
[m,n] = size(image);
potential = zeros(m,n);
for ii=2:m-1
    for jj=2:n-1
        potential(ii,jj) = caculateHuber(image(ii,jj),image(ii-1,jj),delta)+...
            caculateHuber(image(ii,jj),image(ii+1,jj),delta)+...
            caculateHuber(image(ii,jj),image(ii,jj-1),delta)+...
            caculateHuber(image(ii,jj),image(ii,jj+1),delta)+...
            1/(sqrt(2))*caculateHuber(image(ii,jj),image(ii-1,jj-1),delta)+...
            1/(sqrt(2))*caculateHuber(image(ii,jj),image(ii+1,jj-1),delta)+...
            1/(sqrt(2))*caculateHuber(image(ii,jj),image(ii-1,jj+1),delta)+...
            1/(sqrt(2))*caculateHuber(image(ii,jj),image(ii+1,jj+1),delta);
    end
end
end

